webtalk_init -webtalk_dir K:\\sola\\isa_test_20190812\\project_1\\project_1.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-08-13 19:24:41" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "uc139g267lld43kruqi8cl5rj1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_15" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "15" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3192 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.131 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1565677881394" -context "sdk\\\\application/1565677881394"
webtalk_add_data -client sdk -key os -value "linux" -context "sdk\\\\application/1565677881394"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1565677881394"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1565677881394"
webtalk_add_data -client sdk -key LangUsed -value "CPP" -context "sdk\\\\application/1565677881394"
webtalk_add_data -client sdk -key Procused -value "" -context "sdk\\\\application/1565677881394"
webtalk_add_data -client sdk -key projSize -value "127.4921875" -context "sdk\\\\application/1565677881394"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1565695481696"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1565695481696"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1565695481696"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1565695481696"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1565695481696"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1565695481696"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1565695481696"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1565695481696"
webtalk_transmit -clientid 2278008519 -regid "" -xml K:\\sola\\isa_test_20190812\\project_1\\project_1.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html K:\\sola\\isa_test_20190812\\project_1\\project_1.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm K:\\sola\\isa_test_20190812\\project_1\\project_1.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
