// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_sobel_filter (
hls::stream<ap_uint<32> > (&inter_pix),
hls::stream<ap_uint<32> > (&out_pix),
int rows,
int cols);
