// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// ==============================================================

#define AP_INT_MAX_W 32678

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"
#include "hls_signal_handler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "inter_pix_V_V"
#define AUTOTB_TVIN_inter_pix_V_V  "../tv/cdatafile/c.sobel_filter.autotvin_inter_pix_V_V.dat"
#define WRAPC_STREAM_SIZE_IN_inter_pix_V_V  "../tv/stream_size/stream_size_in_inter_pix_V_V.dat"
#define WRAPC_STREAM_INGRESS_STATUS_inter_pix_V_V  "../tv/stream_size/stream_ingress_status_inter_pix_V_V.dat"
// wrapc file define: "out_pix_V_V"
#define AUTOTB_TVOUT_out_pix_V_V  "../tv/cdatafile/c.sobel_filter.autotvout_out_pix_V_V.dat"
#define AUTOTB_TVIN_out_pix_V_V  "../tv/cdatafile/c.sobel_filter.autotvin_out_pix_V_V.dat"
#define WRAPC_STREAM_SIZE_OUT_out_pix_V_V  "../tv/stream_size/stream_size_out_out_pix_V_V.dat"
#define WRAPC_STREAM_EGRESS_STATUS_out_pix_V_V  "../tv/stream_size/stream_egress_status_out_pix_V_V.dat"
// wrapc file define: "rows"
#define AUTOTB_TVIN_rows  "../tv/cdatafile/c.sobel_filter.autotvin_rows.dat"
// wrapc file define: "cols"
#define AUTOTB_TVIN_cols  "../tv/cdatafile/c.sobel_filter.autotvin_cols.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "out_pix_V_V"
#define AUTOTB_TVOUT_PC_out_pix_V_V  "../tv/rtldatafile/rtl.sobel_filter.autotvout_out_pix_V_V.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			inter_pix_V_V_depth = 0;
			out_pix_V_V_depth = 0;
			rows_depth = 0;
			cols_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{inter_pix_V_V " << inter_pix_V_V_depth << "}\n";
			total_list << "{out_pix_V_V " << out_pix_V_V_depth << "}\n";
			total_list << "{rows " << rows_depth << "}\n";
			total_list << "{cols " << cols_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int inter_pix_V_V_depth;
		int out_pix_V_V_depth;
		int rows_depth;
		int cols_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};

extern void sobel_filter (
hls::stream<ap_uint<32> > (&inter_pix),
hls::stream<ap_uint<32> > (&out_pix),
int rows,
int cols);

void AESL_WRAP_sobel_filter (
hls::stream<ap_uint<32> > (&inter_pix),
hls::stream<ap_uint<32> > (&out_pix),
int rows,
int cols)
{
	refine_signal_handler();
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		CodeState = ENTER_WRAPC_PC;
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;

		// pop stream input: "inter_pix"
		aesl_fh.read(WRAPC_STREAM_SIZE_IN_inter_pix_V_V, AESL_token); // [[transaction]]
		aesl_fh.read(WRAPC_STREAM_SIZE_IN_inter_pix_V_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(WRAPC_STREAM_SIZE_IN_inter_pix_V_V, AESL_token); // pop_size
			int aesl_tmp_1 = atoi(AESL_token.c_str());
			for (int i = 0; i < aesl_tmp_1; i++)
			{
				inter_pix.read();
			}
			aesl_fh.read(WRAPC_STREAM_SIZE_IN_inter_pix_V_V, AESL_token); // [[/transaction]]
		}

		// define output stream variables: "out_pix"
		std::vector<ap_uint<32> > aesl_tmp_3;
		int aesl_tmp_4;
		int aesl_tmp_5 = 0;

		// read output stream size: "out_pix"
		aesl_fh.read(WRAPC_STREAM_SIZE_OUT_out_pix_V_V, AESL_token); // [[transaction]]
		aesl_fh.read(WRAPC_STREAM_SIZE_OUT_out_pix_V_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(WRAPC_STREAM_SIZE_OUT_out_pix_V_V, AESL_token); // pop_size
			aesl_tmp_4 = atoi(AESL_token.c_str());
			aesl_fh.read(WRAPC_STREAM_SIZE_OUT_out_pix_V_V, AESL_token); // [[/transaction]]
		}

		// output port post check: "out_pix_V_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_out_pix_V_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_out_pix_V_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_out_pix_V_V, AESL_token); // data

			std::vector<sc_bv<32> > out_pix_V_V_pc_buffer;
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'out_pix_V_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'out_pix_V_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					out_pix_V_V_pc_buffer.push_back(AESL_token.c_str());
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_out_pix_V_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_out_pix_V_V))
				{
					exit(1);
				}
			}

			// correct the buffer size the current transaction
			if (i != aesl_tmp_4)
			{
				aesl_tmp_4 = i;
			}

			if (aesl_tmp_4 > 0 && aesl_tmp_3.size() < aesl_tmp_4)
			{
				int aesl_tmp_3_size = aesl_tmp_3.size();

				for (int tmp_aesl_tmp_3 = 0; tmp_aesl_tmp_3 < aesl_tmp_4 - aesl_tmp_3_size; tmp_aesl_tmp_3++)
				{
					ap_uint<32> tmp;
					aesl_tmp_3.push_back(tmp);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: out_pix_V_V
				{
					// bitslice(31, 0)
					// {
						// celement: out_pix.V.V(31, 0)
						// {
							sc_lv<32>* out_pix_V_V_lv0_0_0_1 = new sc_lv<32>[aesl_tmp_4 - aesl_tmp_5];
						// }
					// }

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: out_pix.V.V(31, 0)
						{
							// carray: (aesl_tmp_5) => (aesl_tmp_4 - 1) @ (1)
							for (int i_0 = aesl_tmp_5; i_0 <= aesl_tmp_4 - 1; i_0 += 1)
							{
								if (&(aesl_tmp_3[0]) != NULL) // check the null address if the c port is array or others
								{
									out_pix_V_V_lv0_0_0_1[hls_map_index].range(31, 0) = sc_bv<32>(out_pix_V_V_pc_buffer[hls_map_index].range(31, 0));
									hls_map_index++;
								}
							}
						}
					}

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: out_pix.V.V(31, 0)
						{
							// carray: (aesl_tmp_5) => (aesl_tmp_4 - 1) @ (1)
							for (int i_0 = aesl_tmp_5; i_0 <= aesl_tmp_4 - 1; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : aesl_tmp_3[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : aesl_tmp_3[0]
								// output_left_conversion : aesl_tmp_3[i_0]
								// output_type_conversion : (out_pix_V_V_lv0_0_0_1[hls_map_index]).to_string(SC_BIN).c_str()
								if (&(aesl_tmp_3[0]) != NULL) // check the null address if the c port is array or others
								{
									aesl_tmp_3[i_0] = (out_pix_V_V_lv0_0_0_1[hls_map_index]).to_string(SC_BIN).c_str();
									hls_map_index++;
								}
							}
						}
					}
				}
			}
		}

		// push back output stream: "out_pix"
		for (int i = 0; i < aesl_tmp_4; i++)
		{
			out_pix.write(aesl_tmp_3[i]);
		}

		AESL_transaction_pc++;
	}
	else
	{
		CodeState = ENTER_WRAPC;
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "inter_pix_V_V"
		char* tvin_inter_pix_V_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_inter_pix_V_V);
		char* wrapc_stream_size_in_inter_pix_V_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_IN_inter_pix_V_V);
		char* wrapc_stream_ingress_status_inter_pix_V_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_INGRESS_STATUS_inter_pix_V_V);

		// "out_pix_V_V"
		char* tvin_out_pix_V_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_out_pix_V_V);
		char* tvout_out_pix_V_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_out_pix_V_V);
		char* wrapc_stream_size_out_out_pix_V_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_OUT_out_pix_V_V);
		char* wrapc_stream_egress_status_out_pix_V_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_EGRESS_STATUS_out_pix_V_V);

		// "rows"
		char* tvin_rows = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_rows);

		// "cols"
		char* tvin_cols = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_cols);

		CodeState = DUMP_INPUTS;
		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// dump stream tvin: "inter_pix"
		std::vector<ap_uint<32> > aesl_tmp_0;
		int aesl_tmp_1 = 0;
		while (!inter_pix.empty())
		{
			aesl_tmp_0.push_back(inter_pix.read());
			aesl_tmp_1++;
		}

		// dump stream tvin: "out_pix"
		std::vector<ap_uint<32> > aesl_tmp_3;
		int aesl_tmp_4 = 0;
		while (!out_pix.empty())
		{
			aesl_tmp_3.push_back(out_pix.read());
			aesl_tmp_4++;
		}

		// [[transaction]]
		sprintf(tvin_rows, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_rows, tvin_rows);

		sc_bv<32> rows_tvin_wrapc_buffer;

		// RTL Name: rows
		{
			// bitslice(31, 0)
			{
				// celement: rows(31, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : rows
						// sub_1st_elem          : 
						// ori_name_1st_elem     : rows
						// regulate_c_name       : rows
						// input_type_conversion : rows
						if (&(rows) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> rows_tmp_mem;
							rows_tmp_mem = rows;
							rows_tvin_wrapc_buffer.range(31, 0) = rows_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_rows, "%s\n", (rows_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_rows, tvin_rows);
		}

		tcl_file.set_num(1, &tcl_file.rows_depth);
		sprintf(tvin_rows, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_rows, tvin_rows);

		// [[transaction]]
		sprintf(tvin_cols, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_cols, tvin_cols);

		sc_bv<32> cols_tvin_wrapc_buffer;

		// RTL Name: cols
		{
			// bitslice(31, 0)
			{
				// celement: cols(31, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : cols
						// sub_1st_elem          : 
						// ori_name_1st_elem     : cols
						// regulate_c_name       : cols
						// input_type_conversion : cols
						if (&(cols) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> cols_tmp_mem;
							cols_tmp_mem = cols;
							cols_tvin_wrapc_buffer.range(31, 0) = cols_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_cols, "%s\n", (cols_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_cols, tvin_cols);
		}

		tcl_file.set_num(1, &tcl_file.cols_depth);
		sprintf(tvin_cols, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_cols, tvin_cols);

		// push back input stream: "inter_pix"
		for (int i = 0; i < aesl_tmp_1; i++)
		{
			inter_pix.write(aesl_tmp_0[i]);
		}

		// push back input stream: "out_pix"
		for (int i = 0; i < aesl_tmp_4; i++)
		{
			out_pix.write(aesl_tmp_3[i]);
		}

// [call_c_dut] ---------->

		CodeState = CALL_C_DUT;
		sobel_filter(inter_pix, out_pix, rows, cols);

		CodeState = DUMP_OUTPUTS;
		// record input size to tv3: "inter_pix"
		int aesl_tmp_2 = inter_pix.size();

		// pop output stream: "out_pix"
		int aesl_tmp_5 = aesl_tmp_4;
		aesl_tmp_4 = 0;
     aesl_tmp_3.clear();
		while (!out_pix.empty())
		{
			aesl_tmp_3.push_back(out_pix.read());
			aesl_tmp_4++;
		}

		// [[transaction]]
		sprintf(tvin_inter_pix_V_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_inter_pix_V_V, tvin_inter_pix_V_V);
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_inter_pix_V_V, tvin_inter_pix_V_V);

		sc_bv<32>* inter_pix_V_V_tvin_wrapc_buffer = new sc_bv<32>[aesl_tmp_1 - aesl_tmp_2];

		// RTL Name: inter_pix_V_V
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: inter_pix.V.V(31, 0)
				{
					// carray: (0) => (aesl_tmp_1 - aesl_tmp_2 - 1) @ (1)
					for (int i_0 = 0; i_0 <= aesl_tmp_1 - aesl_tmp_2 - 1; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : aesl_tmp_0[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : aesl_tmp_0[0]
						// regulate_c_name       : inter_pix_V_V
						// input_type_conversion : (aesl_tmp_0[i_0]).to_string(2).c_str()
						if (&(aesl_tmp_0[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> inter_pix_V_V_tmp_mem;
							inter_pix_V_V_tmp_mem = (aesl_tmp_0[i_0]).to_string(2).c_str();
							inter_pix_V_V_tvin_wrapc_buffer[hls_map_index].range(31, 0) = inter_pix_V_V_tmp_mem.range(31, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_1 - aesl_tmp_2; i++)
		{
			sprintf(tvin_inter_pix_V_V, "%s\n", (inter_pix_V_V_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_inter_pix_V_V, tvin_inter_pix_V_V);
		}

		// dump stream ingress status to file
		sc_int<32> stream_ingress_size_inter_pix_V_V = aesl_tmp_1;
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_inter_pix_V_V, stream_ingress_size_inter_pix_V_V.to_string().c_str());
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_inter_pix_V_V, "\n");

		for (int i = 0; i < aesl_tmp_1 - aesl_tmp_2; i++)
		{
			stream_ingress_size_inter_pix_V_V--;
			aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_inter_pix_V_V, stream_ingress_size_inter_pix_V_V.to_string().c_str());
			aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_inter_pix_V_V, "\n");
		}

		tcl_file.set_num(aesl_tmp_1 - aesl_tmp_2, &tcl_file.inter_pix_V_V_depth);
		sprintf(tvin_inter_pix_V_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_inter_pix_V_V, tvin_inter_pix_V_V);
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_inter_pix_V_V, tvin_inter_pix_V_V);

		// release memory allocation
		delete [] inter_pix_V_V_tvin_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_in_inter_pix_V_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_inter_pix_V_V, wrapc_stream_size_in_inter_pix_V_V);
		sprintf(wrapc_stream_size_in_inter_pix_V_V, "%d\n", aesl_tmp_1 - aesl_tmp_2);
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_inter_pix_V_V, wrapc_stream_size_in_inter_pix_V_V);
		sprintf(wrapc_stream_size_in_inter_pix_V_V, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_inter_pix_V_V, wrapc_stream_size_in_inter_pix_V_V);

		// [[transaction]]
		sprintf(tvout_out_pix_V_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_out_pix_V_V, tvout_out_pix_V_V);

		sc_bv<32>* out_pix_V_V_tvout_wrapc_buffer = new sc_bv<32>[aesl_tmp_4 - aesl_tmp_5];

		// RTL Name: out_pix_V_V
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: out_pix.V.V(31, 0)
				{
					// carray: (aesl_tmp_5) => (aesl_tmp_4 - 1) @ (1)
					for (int i_0 = aesl_tmp_5; i_0 <= aesl_tmp_4 - 1; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : aesl_tmp_3[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : aesl_tmp_3[0]
						// regulate_c_name       : out_pix_V_V
						// input_type_conversion : (aesl_tmp_3[i_0]).to_string(2).c_str()
						if (&(aesl_tmp_3[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> out_pix_V_V_tmp_mem;
							out_pix_V_V_tmp_mem = (aesl_tmp_3[i_0]).to_string(2).c_str();
							out_pix_V_V_tvout_wrapc_buffer[hls_map_index].range(31, 0) = out_pix_V_V_tmp_mem.range(31, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_4 - aesl_tmp_5; i++)
		{
			sprintf(tvout_out_pix_V_V, "%s\n", (out_pix_V_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_out_pix_V_V, tvout_out_pix_V_V);
		}

		tcl_file.set_num(aesl_tmp_4 - aesl_tmp_5, &tcl_file.out_pix_V_V_depth);
		sprintf(tvout_out_pix_V_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_out_pix_V_V, tvout_out_pix_V_V);

		// release memory allocation
		delete [] out_pix_V_V_tvout_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_out_out_pix_V_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_pix_V_V, wrapc_stream_size_out_out_pix_V_V);
		sprintf(wrapc_stream_size_out_out_pix_V_V, "%d\n", aesl_tmp_4 - aesl_tmp_5);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_pix_V_V, wrapc_stream_size_out_out_pix_V_V);
		sprintf(wrapc_stream_size_out_out_pix_V_V, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_out_pix_V_V, wrapc_stream_size_out_out_pix_V_V);

		// push back output stream: "out_pix"
		for (int i = 0; i < aesl_tmp_4; i++)
		{
			out_pix.write(aesl_tmp_3[i]);
		}

		CodeState = DELETE_CHAR_BUFFERS;
		// release memory allocation: "inter_pix_V_V"
		delete [] tvin_inter_pix_V_V;
		delete [] wrapc_stream_size_in_inter_pix_V_V;
		// release memory allocation: "out_pix_V_V"
		delete [] tvout_out_pix_V_V;
		delete [] tvin_out_pix_V_V;
		delete [] wrapc_stream_size_out_out_pix_V_V;
		// release memory allocation: "rows"
		delete [] tvin_rows;
		// release memory allocation: "cols"
		delete [] tvin_cols;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);
	}
}

