webtalk_init -webtalk_dir K:\\sola\\int_test_0814_zedboard\\int_test_0814_zedboard.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-08-22 16:21:07" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "vj5t9s25gcbrvq7iogbacelpj1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_23" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "23" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3192 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.131 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1566461685258" -context "sdk\\\\bsp/1566461685258"
webtalk_add_data -client sdk -key hwid -value "1565784179301" -context "sdk\\\\bsp/1566461685258"
webtalk_add_data -client sdk -key os -value "device_tree" -context "sdk\\\\bsp/1566461685258"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1566461685258"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1566461685258"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1566462067303"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1566462067303"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1566462067303"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1566462067303"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1566462067303"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1566462067303"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1566462067303"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1566462067303"
webtalk_transmit -clientid 4051171326 -regid "" -xml K:\\sola\\int_test_0814_zedboard\\int_test_0814_zedboard.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html K:\\sola\\int_test_0814_zedboard\\int_test_0814_zedboard.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm K:\\sola\\int_test_0814_zedboard\\int_test_0814_zedboard.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
