set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[15]}]

set_property PACKAGE_PIN T17 [get_ports {isa_sa[15]}]
set_property PACKAGE_PIN U20 [get_ports {isa_sa[13]}]
set_property PACKAGE_PIN K16 [get_ports {isa_sa[11]}]
set_property PACKAGE_PIN L16 [get_ports {isa_sa[9]}]
set_property PACKAGE_PIN W20 [get_ports {isa_sa[6]}]
set_property PACKAGE_PIN W19 [get_ports {isa_sa[4]}]
set_property PACKAGE_PIN V17 [get_ports {isa_sa[0]}]
set_property PACKAGE_PIN Y18 [get_ports {isa_sa[2]}]
set_property PACKAGE_PIN V18 [get_ports {isa_sa[1]}]
set_property PACKAGE_PIN Y19 [get_ports {isa_sa[3]}]
set_property PACKAGE_PIN W18 [get_ports {isa_sa[5]}]
set_property PACKAGE_PIN V20 [get_ports {isa_sa[7]}]
set_property PACKAGE_PIN L17 [get_ports {isa_sa[8]}]
set_property PACKAGE_PIN J16 [get_ports {isa_sa[10]}]
set_property PACKAGE_PIN T20 [get_ports {isa_sa[12]}]
set_property PACKAGE_PIN R18 [get_ports {isa_sa[14]}]

set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd[15]}]

set_property PACKAGE_PIN L14 [get_ports {isa_sd[8]}]
set_property PACKAGE_PIN F20 [get_ports {isa_sd[1]}]
set_property PACKAGE_PIN F19 [get_ports {isa_sd[0]}]
set_property PACKAGE_PIN E18 [get_ports {isa_sd[2]}]
set_property PACKAGE_PIN E19 [get_ports {isa_sd[3]}]
set_property PACKAGE_PIN D19 [get_ports {isa_sd[4]}]
set_property PACKAGE_PIN D20 [get_ports {isa_sd[5]}]
set_property PACKAGE_PIN B20 [get_ports {isa_sd[7]}]
set_property PACKAGE_PIN C20 [get_ports {isa_sd[6]}]
set_property PACKAGE_PIN P20 [get_ports {isa_sd[9]}]
set_property PACKAGE_PIN U17 [get_ports {isa_sd[11]}]
set_property PACKAGE_PIN N18 [get_ports {isa_sd[13]}]
set_property PACKAGE_PIN Y16 [get_ports {isa_sd[15]}]
set_property PACKAGE_PIN N20 [get_ports {isa_sd[10]}]
set_property PACKAGE_PIN T16 [get_ports {isa_sd[12]}]
set_property PACKAGE_PIN P19 [get_ports {isa_sd[14]}]

set_property IOSTANDARD LVCMOS33 [get_ports dir_isa_in]
set_property IOSTANDARD LVCMOS33 [get_ports dir_isa_out]
set_property IOSTANDARD LVCMOS33 [get_ports dir_isa_sa1]
set_property IOSTANDARD LVCMOS33 [get_ports dir_isa_sa2]
set_property IOSTANDARD LVCMOS33 [get_ports dir_isa_sd1]
set_property IOSTANDARD LVCMOS33 [get_ports dir_isa_sd2]

set_property PACKAGE_PIN P18 [get_ports dir_isa_sd1]
set_property PACKAGE_PIN W15 [get_ports dir_isa_sd2]
set_property PACKAGE_PIN V16 [get_ports dir_isa_sa1]
set_property PACKAGE_PIN R17 [get_ports dir_isa_sa2]
set_property PACKAGE_PIN M19 [get_ports dir_isa_out]
set_property PACKAGE_PIN L15 [get_ports dir_isa_in]

set_property IOSTANDARD LVCMOS33 [get_ports oe_isa_in]
set_property IOSTANDARD LVCMOS33 [get_ports oe_isa_out]
set_property IOSTANDARD LVCMOS33 [get_ports oe_isa_sa2]
set_property IOSTANDARD LVCMOS33 [get_ports oe_isa_sa1]
set_property IOSTANDARD LVCMOS33 [get_ports oe_isa_sd2]
set_property IOSTANDARD LVCMOS33 [get_ports oe_isa_sd1]

set_property PACKAGE_PIN N17 [get_ports oe_isa_sd1]
set_property PACKAGE_PIN Y17 [get_ports oe_isa_sd2]
set_property PACKAGE_PIN W16 [get_ports oe_isa_sa1]
set_property PACKAGE_PIN R16 [get_ports oe_isa_sa2]
set_property PACKAGE_PIN M14 [get_ports oe_isa_in]
set_property PACKAGE_PIN M20 [get_ports oe_isa_out]

set_property IOSTANDARD LVCMOS33 [get_ports isa_aen]
set_property IOSTANDARD LVCMOS33 [get_ports isa_rst_drv]
set_property IOSTANDARD LVCMOS33 [get_ports isa_ior]
set_property IOSTANDARD LVCMOS33 [get_ports isa_iow]

set_property PACKAGE_PIN P15 [get_ports isa_iow]
set_property PACKAGE_PIN P16 [get_ports isa_ior]
set_property PACKAGE_PIN L20 [get_ports isa_aen]
set_property PACKAGE_PIN L19 [get_ports isa_rst_drv]

set_property IOSTANDARD LVCMOS33 [get_ports iocs16]
#set_property IOSTANDARD LVCMOS33 [get_ports sbhe]
set_property IOSTANDARD LVCMOS33 [get_ports irq5]

set_property PACKAGE_PIN M15 [get_ports iocs16]
#set_property PACKAGE_PIN N15 [get_ports sbhe]
set_property PACKAGE_PIN N16 [get_ports irq5]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/clk_wiz_0/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {isa_sd_IBUF[0]} {isa_sd_IBUF[1]} {isa_sd_IBUF[2]} {isa_sd_IBUF[3]} {isa_sd_IBUF[4]} {isa_sd_IBUF[5]} {isa_sd_IBUF[6]} {isa_sd_IBUF[7]} {isa_sd_IBUF[8]} {isa_sd_IBUF[9]} {isa_sd_IBUF[10]} {isa_sd_IBUF[11]} {isa_sd_IBUF[12]} {isa_sd_IBUF[13]} {isa_sd_IBUF[14]} {isa_sd_IBUF[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {isa_sd_OBUF[0]} {isa_sd_OBUF[1]} {isa_sd_OBUF[2]} {isa_sd_OBUF[3]} {isa_sd_OBUF[4]} {isa_sd_OBUF[5]} {isa_sd_OBUF[6]} {isa_sd_OBUF[7]} {isa_sd_OBUF[8]} {isa_sd_OBUF[9]} {isa_sd_OBUF[10]} {isa_sd_OBUF[11]} {isa_sd_OBUF[12]} {isa_sd_OBUF[13]} {isa_sd_OBUF[14]} {isa_sd_OBUF[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 16 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/axi_isa_v1_0_0_isa_sa[0]} {design_1_i/axi_isa_v1_0_0_isa_sa[1]} {design_1_i/axi_isa_v1_0_0_isa_sa[2]} {design_1_i/axi_isa_v1_0_0_isa_sa[3]} {design_1_i/axi_isa_v1_0_0_isa_sa[4]} {design_1_i/axi_isa_v1_0_0_isa_sa[5]} {design_1_i/axi_isa_v1_0_0_isa_sa[6]} {design_1_i/axi_isa_v1_0_0_isa_sa[7]} {design_1_i/axi_isa_v1_0_0_isa_sa[8]} {design_1_i/axi_isa_v1_0_0_isa_sa[9]} {design_1_i/axi_isa_v1_0_0_isa_sa[10]} {design_1_i/axi_isa_v1_0_0_isa_sa[11]} {design_1_i/axi_isa_v1_0_0_isa_sa[12]} {design_1_i/axi_isa_v1_0_0_isa_sa[13]} {design_1_i/axi_isa_v1_0_0_isa_sa[14]} {design_1_i/axi_isa_v1_0_0_isa_sa[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list design_1_i/axi_isa_v1_0_0_dir_isa_sd1]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/axi_isa_v1_0_0_isa_aen]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/axi_isa_v1_0_0_isa_ior]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list design_1_i/axi_isa_v1_0_0_isa_iow]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list design_1_i/axi_isa_v1_0_0_oe_isa_sd1]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list design_1_i/iocs16_0_1]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list design_1_i/irq5_0_1]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 1 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list design_1_i/axi_isa_v1_0_0_isa_rst_drv]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_1_FCLK_CLK0]
